<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HCH6RMM" failures="10" tests="124" name="runner.TestRunner" time="113.608" errors="1" timestamp="2023-08-19T13:19:07 EDT" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="0.884"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.877">
    <failure message="expected [Username already exists] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Username already exists] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.C_Register_SD.it_should_display_an_error_message(C_Register_SD.java:79)
at ✽.It should display an error message "Username already exists"(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:98)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.001"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.361"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.189"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.735"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.790"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.453"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.413"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.471"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.395"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.432"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.317"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.883"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.246"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.502"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.363"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.032"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.264"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.286"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.794"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.493"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.816">
    <failure message="expected [Please check your password] but found [Invalid Username and Password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please check your password] but found [Invalid Username and Password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.D_SignIn_SD.click_login_button(D_SignIn_SD.java:119)
at ✽.click login button(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/4_SignIn.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.767"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.144"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.750"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.466"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.428"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.771"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.319"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.400"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.351"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.849">
    <failure message="expected [Password can’t be entirely numeric.] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Password can’t be entirely numeric.] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.C_Register_SD.it_should_display_an_error_message(C_Register_SD.java:79)
at ✽.It should display an error message "Password can’t be entirely numeric."(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:74)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.414"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.568"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.839"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.715"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.798"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.879"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.743"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.503"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.063"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.228"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.340"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.410"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.317"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.094"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.259"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.316"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.306"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.721"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.861">
    <failure message="expected [password can’t be too similar to your other personal information.] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password can’t be too similar to your other personal information.] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.C_Register_SD.it_should_display_an_error_message(C_Register_SD.java:79)
at ✽.It should display an error message "password can’t be too similar to your other personal information."(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:82)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.773"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.230"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.058"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.927"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.312"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.500"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.270"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.848"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.172"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.617"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.550"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.735"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.783"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.877"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.212"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.653"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.687"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.483"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.859">
    <failure message="expected [Password can’t be commonly used password] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Password can’t be commonly used password] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.C_Register_SD.it_should_display_an_error_message(C_Register_SD.java:79)
at ✽.It should display an error message "Password can’t be commonly used password"(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:90)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.434"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.514"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.678"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.814"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.379"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.476"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.710"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.615"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.761"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.729"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.941">
    <failure message="Result do not match expected [null] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [null] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at StepDefinition.F_Array_SD.the_user_should_be_presented_with_successful_submission_message(F_Array_SD.java:109)
at ✽.The user should be presented with successful submission message(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/6_Array.feature:149)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.351"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.457"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.365"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.227"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.726"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.355">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;//a[@href=&#039;/logout&#039;]&quot;}
  (Session info: chrome=116.0.5845.97)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.11.0&#039;, revision: &#039;040bc5406b&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.7&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ab6d9cb20c098db6202cc62f2dda0a12, findElement {using=xpath, value=//a[@href=&#039;/logout&#039;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 116.0.5845.97, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: C:\Users\limna\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62308}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62308/devtoo..., se:cdpVersion: 116.0.5845.97, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: ab6d9cb20c098db6202cc62f2dda0a12" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@href='/logout']"}
  (Session info: chrome=116.0.5845.97)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ab6d9cb20c098db6202cc62f2dda0a12, findElement {using=xpath, value=//a[@href='/logout']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 116.0.5845.97, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: C:\Users\limna\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62308}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62308/devtoo..., se:cdpVersion: 116.0.5845.97, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: ab6d9cb20c098db6202cc62f2dda0a12
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy33.click(Unknown Source)
at pageObjects.RegisterPage.clickSignout(RegisterPage.java:133)
at StepDefinition.C_Register_SD.the_user_clicks_the_link(C_Register_SD.java:173)
at ✽.The user clicks the "Sign Out" link(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:120)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.226"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.749"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.214"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.148"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.801"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.326"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.336"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.102">
    <failure message="Title mismatch expected [NumpyNinja] but found [ProgrammingError at /register]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Title mismatch expected [NumpyNinja] but found [ProgrammingError at /register]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at StepDefinition.C_Register_SD.the_user_should_be_redirected_to_homepage_with_the_message(C_Register_SD.java:134)
at ✽.The user should be redirected to Homepage with the message "New Account Created. You are logged in as <username>"(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:105)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.773"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.914">
    <failure message="expected [Password should contain at least 8 characters] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Password should contain at least 8 characters] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.C_Register_SD.it_should_display_an_error_message(C_Register_SD.java:79)
at ✽.It should display an error message "Password should contain at least 8 characters"(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:66)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.278"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.460"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.710"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.411"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.490"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.499"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.333"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.891"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.481"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.536"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.815"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.686"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.914">
    <failure message="expected [Please enter a valid username] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please enter a valid username] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.C_Register_SD.it_should_display_an_error_message(C_Register_SD.java:79)
at ✽.It should display an error message "Please enter a valid username"(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/3_Register.feature:51)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.487"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.467"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.616"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.273"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.701"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.984">
    <failure message="expected [Please check your user id] but found [Invalid Username and Password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please check your user id] but found [Invalid Username and Password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.D_SignIn_SD.click_login_button(D_SignIn_SD.java:119)
at ✽.click login button(file:///C:/Users/limna/git/repository/SDET_Algo/src/test/resources/features/4_SignIn.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.768"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.665"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.832"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.241"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.388"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.719"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.680"/>
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
